version: '3.9'
services:
  development:
    container_name: app-06-sign-up-firebase
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - /workspaces/app-06-sign-up-firebase/node_modules
